spring.application.name=transaction-service

server.port=8084

spring.datasource.url=jdbc:mysql://database-1.c6fso2qmuuv2.us-east-1.rds.amazonaws.com:3306/bankingdb
spring.datasource.username=admin
spring.datasource.password=admin1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
